version: '3'
services:
  proxy:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
  blue-app:
    image: nginx:alpine
    volumes:
      - ./index-blue.html:/usr/share/nginx/html/index.html:ro
  green-app:
    image: nginx:alpine
    volumes:
      - ./index-green.html:/usr/share/nginx/html/index.html:ro
